// Interface pour les données d'un pays africain
export interface AfricanCountry {
    country_code: string
    name: string
    name_fr: string
    capital: string
    capital_fr: string
    currency: string
    currency_symbol: string
    phone_code: string
    flag_emoji: string
    region: string
    subregion: string
    population: number
    area_km2: number
    languages: string[]
    coordinates: {
        lat: number
        lng: number
    }
    timezone: string
    is_supported: boolean
}

// Données complètes des pays africains pour AfricaHub
export const AFRICA_COUNTRIES: Record<string, AfricanCountry> = {
    DZ: {
        country_code: "DZ",
        name: "Algeria",
        name_fr: "Algérie",
        capital: "Algiers",
        capital_fr: "Alger",
        currency: "DZD",
        currency_symbol: "د.ج",
        phone_code: "+213",
        flag_emoji: "🇩🇿",
        region: "Africa",
        subregion: "Northern Africa",
        population: 44700000,
        area_km2: 2381741,
        languages: ["Arabic", "Berber"],
        coordinates: { lat: 28.0339, lng: 1.6596 },
        timezone: "Africa/Algiers",
        is_supported: true,
    },
    AO: {
        country_code: "AO",
        name: "Angola",
        name_fr: "Angola",
        capital: "Luanda",
        capital_fr: "Luanda",
        currency: "AOA",
        currency_symbol: "Kz",
        phone_code: "+244",
        flag_emoji: "🇦🇴",
        region: "Africa",
        subregion: "Middle Africa",
        population: 33933610,
        area_km2: 1246700,
        languages: ["Portuguese"],
        coordinates: { lat: -11.2027, lng: 17.8739 },
        timezone: "Africa/Luanda",
        is_supported: true,
    },
    BJ: {
        country_code: "BJ",
        name: "Benin",
        name_fr: "Bénin",
        capital: "Porto-Novo",
        capital_fr: "Porto-Novo",
        currency: "XOF",
        currency_symbol: "CFA",
        phone_code: "+229",
        flag_emoji: "🇧🇯",
        region: "Africa",
        subregion: "Western Africa",
        population: 12451040,
        area_km2: 112622,
        languages: ["French"],
        coordinates: { lat: 9.3077, lng: 2.3158 },
        timezone: "Africa/Porto-Novo",
        is_supported: true,
    },
    BW: {
        country_code: "BW",
        name: "Botswana",
        name_fr: "Botswana",
        capital: "Gaborone",
        capital_fr: "Gaborone",
        currency: "BWP",
        currency_symbol: "P",
        phone_code: "+267",
        flag_emoji: "🇧🇼",
        region: "Africa",
        subregion: "Southern Africa",
        population: 2397240,
        area_km2: 581730,
        languages: ["English", "Tswana"],
        coordinates: { lat: -22.3285, lng: 24.6849 },
        timezone: "Africa/Gaborone",
        is_supported: true,
    },
    BF: {
        country_code: "BF",
        name: "Burkina Faso",
        name_fr: "Burkina Faso",
        capital: "Ouagadougou",
        capital_fr: "Ouagadougou",
        currency: "XOF",
        currency_symbol: "CFA",
        phone_code: "+226",
        flag_emoji: "🇧🇫",
        region: "Africa",
        subregion: "Western Africa",
        population: 21497096,
        area_km2: 274200,
        languages: ["French"],
        coordinates: { lat: 12.2383, lng: -1.5616 },
        timezone: "Africa/Ouagadougou",
        is_supported: true,
    },
    BI: {
        country_code: "BI",
        name: "Burundi",
        name_fr: "Burundi",
        capital: "Gitega",
        capital_fr: "Gitega",
        currency: "BIF",
        currency_symbol: "FBu",
        phone_code: "+257",
        flag_emoji: "🇧🇮",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 12255429,
        area_km2: 27830,
        languages: ["Kirundi", "French", "English"],
        coordinates: { lat: -3.3731, lng: 29.9189 },
        timezone: "Africa/Bujumbura",
        is_supported: true,
    },
    CV: {
        country_code: "CV",
        name: "Cape Verde",
        name_fr: "Cap-Vert",
        capital: "Praia",
        capital_fr: "Praia",
        currency: "CVE",
        currency_symbol: "$",
        phone_code: "+238",
        flag_emoji: "🇨🇻",
        region: "Africa",
        subregion: "Western Africa",
        population: 555987,
        area_km2: 4033,
        languages: ["Portuguese"],
        coordinates: { lat: 16.5388, lng: -24.0132 },
        timezone: "Atlantic/Cape_Verde",
        is_supported: true,
    },
    CM: {
        country_code: "CM",
        name: "Cameroon",
        name_fr: "Cameroun",
        capital: "Yaoundé",
        capital_fr: "Yaoundé",
        currency: "XAF",
        currency_symbol: "FCFA",
        phone_code: "+237",
        flag_emoji: "🇨🇲",
        region: "Africa",
        subregion: "Middle Africa",
        population: 27224265,
        area_km2: 475442,
        languages: ["English", "French"],
        coordinates: { lat: 7.3697, lng: 12.3547 },
        timezone: "Africa/Douala",
        is_supported: true,
    },
    CF: {
        country_code: "CF",
        name: "Central African Republic",
        name_fr: "République Centrafricaine",
        capital: "Bangui",
        capital_fr: "Bangui",
        currency: "XAF",
        currency_symbol: "FCFA",
        phone_code: "+236",
        flag_emoji: "🇨🇫",
        region: "Africa",
        subregion: "Middle Africa",
        population: 4829767,
        area_km2: 622984,
        languages: ["French", "Sango"],
        coordinates: { lat: 6.6111, lng: 20.9394 },
        timezone: "Africa/Bangui",
        is_supported: true,
    },
    TD: {
        country_code: "TD",
        name: "Chad",
        name_fr: "Tchad",
        capital: "N'Djamena",
        capital_fr: "N'Djamena",
        currency: "XAF",
        currency_symbol: "FCFA",
        phone_code: "+235",
        flag_emoji: "🇹🇩",
        region: "Africa",
        subregion: "Middle Africa",
        population: 16425864,
        area_km2: 1284000,
        languages: ["French", "Arabic"],
        coordinates: { lat: 15.4542, lng: 18.7322 },
        timezone: "Africa/Ndjamena",
        is_supported: true,
    },
    KM: {
        country_code: "KM",
        name: "Comoros",
        name_fr: "Comores",
        capital: "Moroni",
        capital_fr: "Moroni",
        currency: "KMF",
        currency_symbol: "CF",
        phone_code: "+269",
        flag_emoji: "🇰🇲",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 869601,
        area_km2: 2235,
        languages: ["Arabic", "French", "Comorian"],
        coordinates: { lat: -11.6455, lng: 43.3333 },
        timezone: "Indian/Comoro",
        is_supported: true,
    },
    CG: {
        country_code: "CG",
        name: "Republic of the Congo",
        name_fr: "République du Congo",
        capital: "Brazzaville",
        capital_fr: "Brazzaville",
        currency: "XAF",
        currency_symbol: "FCFA",
        phone_code: "+242",
        flag_emoji: "🇨🇬",
        region: "Africa",
        subregion: "Middle Africa",
        population: 5518087,
        area_km2: 342000,
        languages: ["French"],
        coordinates: { lat: -0.228, lng: 15.8277 },
        timezone: "Africa/Brazzaville",
        is_supported: true,
    },
    CD: {
        country_code: "CD",
        name: "Democratic Republic of the Congo",
        name_fr: "République Démocratique du Congo",
        capital: "Kinshasa",
        capital_fr: "Kinshasa",
        currency: "CDF",
        currency_symbol: "FC",
        phone_code: "+243",
        flag_emoji: "🇨🇩",
        region: "Africa",
        subregion: "Middle Africa",
        population: 89561403,
        area_km2: 2344858,
        languages: ["French"],
        coordinates: { lat: -4.0383, lng: 21.7587 },
        timezone: "Africa/Kinshasa",
        is_supported: true,
    },
    CI: {
        country_code: "CI",
        name: "Côte d'Ivoire",
        name_fr: "Côte d'Ivoire",
        capital: "Yamoussoukro",
        capital_fr: "Yamoussoukro",
        currency: "XOF",
        currency_symbol: "CFA",
        phone_code: "+225",
        flag_emoji: "🇨🇮",
        region: "Africa",
        subregion: "Western Africa",
        population: 26378274,
        area_km2: 322463,
        languages: ["French"],
        coordinates: { lat: 7.54, lng: -5.5471 },
        timezone: "Africa/Abidjan",
        is_supported: true,
    },
    DJ: {
        country_code: "DJ",
        name: "Djibouti",
        name_fr: "Djibouti",
        capital: "Djibouti",
        capital_fr: "Djibouti",
        currency: "DJF",
        currency_symbol: "Fdj",
        phone_code: "+253",
        flag_emoji: "🇩🇯",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 988000,
        area_km2: 23200,
        languages: ["French", "Arabic"],
        coordinates: { lat: 11.8251, lng: 42.5903 },
        timezone: "Africa/Djibouti",
        is_supported: true,
    },
    EG: {
        country_code: "EG",
        name: "Egypt",
        name_fr: "Égypte",
        capital: "Cairo",
        capital_fr: "Le Caire",
        currency: "EGP",
        currency_symbol: "£",
        phone_code: "+20",
        flag_emoji: "🇪🇬",
        region: "Africa",
        subregion: "Northern Africa",
        population: 102334404,
        area_km2: 1001450,
        languages: ["Arabic"],
        coordinates: { lat: 26.0975, lng: 31.2357 },
        timezone: "Africa/Cairo",
        is_supported: true,
    },
    GQ: {
        country_code: "GQ",
        name: "Equatorial Guinea",
        name_fr: "Guinée Équatoriale",
        capital: "Malabo",
        capital_fr: "Malabo",
        currency: "XAF",
        currency_symbol: "FCFA",
        phone_code: "+240",
        flag_emoji: "🇬🇶",
        region: "Africa",
        subregion: "Middle Africa",
        population: 1402985,
        area_km2: 28051,
        languages: ["Spanish", "French", "Portuguese"],
        coordinates: { lat: 1.6508, lng: 10.2679 },
        timezone: "Africa/Malabo",
        is_supported: true,
    },
    ER: {
        country_code: "ER",
        name: "Eritrea",
        name_fr: "Érythrée",
        capital: "Asmara",
        capital_fr: "Asmara",
        currency: "ERN",
        currency_symbol: "Nfk",
        phone_code: "+291",
        flag_emoji: "🇪🇷",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 3546421,
        area_km2: 117600,
        languages: ["Tigrinya", "Arabic", "English"],
        coordinates: { lat: 15.1794, lng: 39.7823 },
        timezone: "Africa/Asmara",
        is_supported: true,
    },
    SZ: {
        country_code: "SZ",
        name: "Eswatini",
        name_fr: "Eswatini",
        capital: "Mbabane",
        capital_fr: "Mbabane",
        currency: "SZL",
        currency_symbol: "L",
        phone_code: "+268",
        flag_emoji: "🇸🇿",
        region: "Africa",
        subregion: "Southern Africa",
        population: 1160164,
        area_km2: 17364,
        languages: ["English", "Swati"],
        coordinates: { lat: -26.5225, lng: 31.4659 },
        timezone: "Africa/Mbabane",
        is_supported: true,
    },
    ET: {
        country_code: "ET",
        name: "Ethiopia",
        name_fr: "Éthiopie",
        capital: "Addis Ababa",
        capital_fr: "Addis-Abeba",
        currency: "ETB",
        currency_symbol: "Br",
        phone_code: "+251",
        flag_emoji: "🇪🇹",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 117876227,
        area_km2: 1104300,
        languages: ["Amharic"],
        coordinates: { lat: 9.145, lng: 40.4897 },
        timezone: "Africa/Addis_Ababa",
        is_supported: true,
    },
    GA: {
        country_code: "GA",
        name: "Gabon",
        name_fr: "Gabon",
        capital: "Libreville",
        capital_fr: "Libreville",
        currency: "XAF",
        currency_symbol: "FCFA",
        phone_code: "+241",
        flag_emoji: "🇬🇦",
        region: "Africa",
        subregion: "Middle Africa",
        population: 2225734,
        area_km2: 267668,
        languages: ["French"],
        coordinates: { lat: 0.4162, lng: 9.4673 },
        timezone: "Africa/Libreville",
        is_supported: true,
    },
    GM: {
        country_code: "GM",
        name: "Gambia",
        name_fr: "Gambie",
        capital: "Banjul",
        capital_fr: "Banjul",
        currency: "GMD",
        currency_symbol: "D",
        phone_code: "+220",
        flag_emoji: "🇬🇲",
        region: "Africa",
        subregion: "Western Africa",
        population: 2416668,
        area_km2: 11295,
        languages: ["English"],
        coordinates: { lat: 13.4432, lng: -15.3101 },
        timezone: "Africa/Banjul",
        is_supported: true,
    },
    GH: {
        country_code: "GH",
        name: "Ghana",
        name_fr: "Ghana",
        capital: "Accra",
        capital_fr: "Accra",
        currency: "GHS",
        currency_symbol: "₵",
        phone_code: "+233",
        flag_emoji: "🇬🇭",
        region: "Africa",
        subregion: "Western Africa",
        population: 31072940,
        area_km2: 238533,
        languages: ["English"],
        coordinates: { lat: 7.9465, lng: -1.0232 },
        timezone: "Africa/Accra",
        is_supported: true,
    },
    GN: {
        country_code: "GN",
        name: "Guinea",
        name_fr: "Guinée",
        capital: "Conakry",
        capital_fr: "Conakry",
        currency: "GNF",
        currency_symbol: "FG",
        phone_code: "+224",
        flag_emoji: "🇬🇳",
        region: "Africa",
        subregion: "Western Africa",
        population: 13132795,
        area_km2: 245857,
        languages: ["French"],
        coordinates: { lat: 9.9456, lng: -9.6966 },
        timezone: "Africa/Conakry",
        is_supported: true,
    },
    GW: {
        country_code: "GW",
        name: "Guinea-Bissau",
        name_fr: "Guinée-Bissau",
        capital: "Bissau",
        capital_fr: "Bissau",
        currency: "XOF",
        currency_symbol: "CFA",
        phone_code: "+245",
        flag_emoji: "🇬🇼",
        region: "Africa",
        subregion: "Western Africa",
        population: 1968001,
        area_km2: 36125,
        languages: ["Portuguese"],
        coordinates: { lat: 11.8037, lng: -15.1804 },
        timezone: "Africa/Bissau",
        is_supported: true,
    },
    KE: {
        country_code: "KE",
        name: "Kenya",
        name_fr: "Kenya",
        capital: "Nairobi",
        capital_fr: "Nairobi",
        currency: "KES",
        currency_symbol: "KSh",
        phone_code: "+254",
        flag_emoji: "🇰🇪",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 53771296,
        area_km2: 580367,
        languages: ["English", "Swahili"],
        coordinates: { lat: -0.0236, lng: 37.9062 },
        timezone: "Africa/Nairobi",
        is_supported: true,
    },
    LS: {
        country_code: "LS",
        name: "Lesotho",
        name_fr: "Lesotho",
        capital: "Maseru",
        capital_fr: "Maseru",
        currency: "LSL",
        currency_symbol: "L",
        phone_code: "+266",
        flag_emoji: "🇱🇸",
        region: "Africa",
        subregion: "Southern Africa",
        population: 2142249,
        area_km2: 30355,
        languages: ["English", "Sesotho"],
        coordinates: { lat: -29.61, lng: 28.2336 },
        timezone: "Africa/Maseru",
        is_supported: true,
    },
    LR: {
        country_code: "LR",
        name: "Liberia",
        name_fr: "Libéria",
        capital: "Monrovia",
        capital_fr: "Monrovia",
        currency: "LRD",
        currency_symbol: "$",
        phone_code: "+231",
        flag_emoji: "🇱🇷",
        region: "Africa",
        subregion: "Western Africa",
        population: 5057681,
        area_km2: 111369,
        languages: ["English"],
        coordinates: { lat: 6.4281, lng: -9.4295 },
        timezone: "Africa/Monrovia",
        is_supported: true,
    },
    LY: {
        country_code: "LY",
        name: "Libya",
        name_fr: "Libye",
        capital: "Tripoli",
        capital_fr: "Tripoli",
        currency: "LYD",
        currency_symbol: "ل.د",
        phone_code: "+218",
        flag_emoji: "🇱🇾",
        region: "Africa",
        subregion: "Northern Africa",
        population: 6871292,
        area_km2: 1759540,
        languages: ["Arabic"],
        coordinates: { lat: 26.3351, lng: 17.2283 },
        timezone: "Africa/Tripoli",
        is_supported: true,
    },
    MG: {
        country_code: "MG",
        name: "Madagascar",
        name_fr: "Madagascar",
        capital: "Antananarivo",
        capital_fr: "Antananarivo",
        currency: "MGA",
        currency_symbol: "Ar",
        phone_code: "+261",
        flag_emoji: "🇲🇬",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 27691018,
        area_km2: 587041,
        languages: ["French", "Malagasy"],
        coordinates: { lat: -18.7669, lng: 46.8691 },
        timezone: "Indian/Antananarivo",
        is_supported: true,
    },
    MW: {
        country_code: "MW",
        name: "Malawi",
        name_fr: "Malawi",
        capital: "Lilongwe",
        capital_fr: "Lilongwe",
        currency: "MWK",
        currency_symbol: "MK",
        phone_code: "+265",
        flag_emoji: "🇲🇼",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 19129952,
        area_km2: 118484,
        languages: ["English", "Chichewa"],
        coordinates: { lat: -13.2543, lng: 34.3015 },
        timezone: "Africa/Blantyre",
        is_supported: true,
    },
    ML: {
        country_code: "ML",
        name: "Mali",
        name_fr: "Mali",
        capital: "Bamako",
        capital_fr: "Bamako",
        currency: "XOF",
        currency_symbol: "CFA",
        phone_code: "+223",
        flag_emoji: "🇲🇱",
        region: "Africa",
        subregion: "Western Africa",
        population: 20250833,
        area_km2: 1240192,
        languages: ["French"],
        coordinates: { lat: 17.5707, lng: -3.9962 },
        timezone: "Africa/Bamako",
        is_supported: true,
    },
    MR: {
        country_code: "MR",
        name: "Mauritania",
        name_fr: "Mauritanie",
        capital: "Nouakchott",
        capital_fr: "Nouakchott",
        currency: "MRU",
        currency_symbol: "UM",
        phone_code: "+222",
        flag_emoji: "🇲🇷",
        region: "Africa",
        subregion: "Western Africa",
        population: 4649658,
        area_km2: 1030700,
        languages: ["Arabic"],
        coordinates: { lat: 21.0079, lng: -10.9408 },
        timezone: "Africa/Nouakchott",
        is_supported: true,
    },
    MU: {
        country_code: "MU",
        name: "Mauritius",
        name_fr: "Maurice",
        capital: "Port Louis",
        capital_fr: "Port-Louis",
        currency: "MUR",
        currency_symbol: "₨",
        phone_code: "+230",
        flag_emoji: "🇲🇺",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 1271768,
        area_km2: 2040,
        languages: ["English", "French"],
        coordinates: { lat: -20.3484, lng: 57.5522 },
        timezone: "Indian/Mauritius",
        is_supported: true,
    },
    MA: {
        country_code: "MA",
        name: "Morocco",
        name_fr: "Maroc",
        capital: "Rabat",
        capital_fr: "Rabat",
        currency: "MAD",
        currency_symbol: "د.م.",
        phone_code: "+212",
        flag_emoji: "🇲🇦",
        region: "Africa",
        subregion: "Northern Africa",
        population: 36910560,
        area_km2: 446550,
        languages: ["Arabic", "Berber"],
        coordinates: { lat: 31.7917, lng: -7.0926 },
        timezone: "Africa/Casablanca",
        is_supported: true,
    },
    MZ: {
        country_code: "MZ",
        name: "Mozambique",
        name_fr: "Mozambique",
        capital: "Maputo",
        capital_fr: "Maputo",
        currency: "MZN",
        currency_symbol: "MT",
        phone_code: "+258",
        flag_emoji: "🇲🇿",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 31255435,
        area_km2: 801590,
        languages: ["Portuguese"],
        coordinates: { lat: -18.6657, lng: 35.5296 },
        timezone: "Africa/Maputo",
        is_supported: true,
    },
    NA: {
        country_code: "NA",
        name: "Namibia",
        name_fr: "Namibie",
        capital: "Windhoek",
        capital_fr: "Windhoek",
        currency: "NAD",
        currency_symbol: "$",
        phone_code: "+264",
        flag_emoji: "🇳🇦",
        region: "Africa",
        subregion: "Southern Africa",
        population: 2540905,
        area_km2: 824292,
        languages: ["English"],
        coordinates: { lat: -22.9576, lng: 18.4904 },
        timezone: "Africa/Windhoek",
        is_supported: true,
    },
    NE: {
        country_code: "NE",
        name: "Niger",
        name_fr: "Niger",
        capital: "Niamey",
        capital_fr: "Niamey",
        currency: "XOF",
        currency_symbol: "CFA",
        phone_code: "+227",
        flag_emoji: "🇳🇪",
        region: "Africa",
        subregion: "Western Africa",
        population: 24206644,
        area_km2: 1267000,
        languages: ["French"],
        coordinates: { lat: 17.6078, lng: 8.0817 },
        timezone: "Africa/Niamey",
        is_supported: true,
    },
    NG: {
        country_code: "NG",
        name: "Nigeria",
        name_fr: "Nigéria",
        capital: "Abuja",
        capital_fr: "Abuja",
        currency: "NGN",
        currency_symbol: "₦",
        phone_code: "+234",
        flag_emoji: "🇳🇬",
        region: "Africa",
        subregion: "Western Africa",
        population: 218541212,
        area_km2: 923768,
        languages: ["English"],
        coordinates: { lat: 9.0765, lng: 8.6753 },
        timezone: "Africa/Lagos",
        is_supported: true,
    },
    RW: {
        country_code: "RW",
        name: "Rwanda",
        name_fr: "Rwanda",
        capital: "Kigali",
        capital_fr: "Kigali",
        currency: "RWF",
        currency_symbol: "FRw",
        phone_code: "+250",
        flag_emoji: "🇷🇼",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 12952218,
        area_km2: 26338,
        languages: ["Kinyarwanda", "French", "English"],
        coordinates: { lat: -1.9403, lng: 29.8739 },
        timezone: "Africa/Kigali",
        is_supported: true,
    },
    ST: {
        country_code: "ST",
        name: "São Tomé and Príncipe",
        name_fr: "São Tomé-et-Príncipe",
        capital: "São Tomé",
        capital_fr: "São Tomé",
        currency: "STN",
        currency_symbol: "Db",
        phone_code: "+239",
        flag_emoji: "🇸🇹",
        region: "Africa",
        subregion: "Middle Africa",
        population: 219159,
        area_km2: 964,
        languages: ["Portuguese"],
        coordinates: { lat: 0.1864, lng: 6.6131 },
        timezone: "Africa/Sao_Tome",
        is_supported: true,
    },
    SN: {
        country_code: "SN",
        name: "Senegal",
        name_fr: "Sénégal",
        capital: "Dakar",
        capital_fr: "Dakar",
        currency: "XOF",
        currency_symbol: "CFA",
        phone_code: "+221",
        flag_emoji: "🇸🇳",
        region: "Africa",
        subregion: "Western Africa",
        population: 16743927,
        area_km2: 196722,
        languages: ["French"],
        coordinates: { lat: 14.4974, lng: -14.4524 },
        timezone: "Africa/Dakar",
        is_supported: true,
    },
    SC: {
        country_code: "SC",
        name: "Seychelles",
        name_fr: "Seychelles",
        capital: "Victoria",
        capital_fr: "Victoria",
        currency: "SCR",
        currency_symbol: "₨",
        phone_code: "+248",
        flag_emoji: "🇸🇨",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 98347,
        area_km2: 452,
        languages: ["English", "French", "Seychellois Creole"],
        coordinates: { lat: -4.6796, lng: 55.492 },
        timezone: "Indian/Mahe",
        is_supported: true,
    },
    SL: {
        country_code: "SL",
        name: "Sierra Leone",
        name_fr: "Sierra Leone",
        capital: "Freetown",
        capital_fr: "Freetown",
        currency: "SLL",
        currency_symbol: "Le",
        phone_code: "+232",
        flag_emoji: "🇸🇱",
        region: "Africa",
        subregion: "Western Africa",
        population: 7976983,
        area_km2: 71740,
        languages: ["English"],
        coordinates: { lat: 8.4606, lng: -11.7799 },
        timezone: "Africa/Freetown",
        is_supported: true,
    },
    SO: {
        country_code: "SO",
        name: "Somalia",
        name_fr: "Somalie",
        capital: "Mogadishu",
        capital_fr: "Mogadiscio",
        currency: "SOS",
        currency_symbol: "S",
        phone_code: "+252",
        flag_emoji: "🇸🇴",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 15893222,
        area_km2: 637657,
        languages: ["Somali", "Arabic"],
        coordinates: { lat: 5.1521, lng: 46.1996 },
        timezone: "Africa/Mogadishu",
        is_supported: true,
    },
    ZA: {
        country_code: "ZA",
        name: "South Africa",
        name_fr: "Afrique du Sud",
        capital: "Cape Town",
        capital_fr: "Le Cap",
        currency: "ZAR",
        currency_symbol: "R",
        phone_code: "+27",
        flag_emoji: "🇿🇦",
        region: "Africa",
        subregion: "Southern Africa",
        population: 59308690,
        area_km2: 1221037,
        languages: ["Afrikaans", "English", "Zulu", "Xhosa"],
        coordinates: { lat: -30.5595, lng: 22.9375 },
        timezone: "Africa/Johannesburg",
        is_supported: true,
    },
    SS: {
        country_code: "SS",
        name: "South Sudan",
        name_fr: "Soudan du Sud",
        capital: "Juba",
        capital_fr: "Juba",
        currency: "SSP",
        currency_symbol: "£",
        phone_code: "+211",
        flag_emoji: "🇸🇸",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 11193725,
        area_km2: 644329,
        languages: ["English"],
        coordinates: { lat: 6.877, lng: 31.307 },
        timezone: "Africa/Juba",
        is_supported: true,
    },
    SD: {
        country_code: "SD",
        name: "Sudan",
        name_fr: "Soudan",
        capital: "Khartoum",
        capital_fr: "Khartoum",
        currency: "SDG",
        currency_symbol: "ج.س.",
        phone_code: "+249",
        flag_emoji: "🇸🇩",
        region: "Africa",
        subregion: "Northern Africa",
        population: 43849260,
        area_km2: 1861484,
        languages: ["Arabic", "English"],
        coordinates: { lat: 12.8628, lng: 30.2176 },
        timezone: "Africa/Khartoum",
        is_supported: true,
    },
    TZ: {
        country_code: "TZ",
        name: "Tanzania",
        name_fr: "Tanzanie",
        capital: "Dodoma",
        capital_fr: "Dodoma",
        currency: "TZS",
        currency_symbol: "TSh",
        phone_code: "+255",
        flag_emoji: "🇹🇿",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 59734218,
        area_km2: 947303,
        languages: ["Swahili", "English"],
        coordinates: { lat: -6.369, lng: 34.8888 },
        timezone: "Africa/Dar_es_Salaam",
        is_supported: true,
    },
    TG: {
        country_code: "TG",
        name: "Togo",
        name_fr: "Togo",
        capital: "Lomé",
        capital_fr: "Lomé",
        currency: "XOF",
        currency_symbol: "CFA",
        phone_code: "+228",
        flag_emoji: "🇹🇬",
        region: "Africa",
        subregion: "Western Africa",
        population: 8278724,
        area_km2: 56785,
        languages: ["French"],
        coordinates: { lat: 8.6195, lng: 0.8248 },
        timezone: "Africa/Lome",
        is_supported: true,
    },
    TN: {
        country_code: "TN",
        name: "Tunisia",
        name_fr: "Tunisie",
        capital: "Tunis",
        capital_fr: "Tunis",
        currency: "TND",
        currency_symbol: "د.ت",
        phone_code: "+216",
        flag_emoji: "🇹🇳",
        region: "Africa",
        subregion: "Northern Africa",
        population: 11818619,
        area_km2: 163610,
        languages: ["Arabic"],
        coordinates: { lat: 33.8869, lng: 9.5375 },
        timezone: "Africa/Tunis",
        is_supported: true,
    },
    UG: {
        country_code: "UG",
        name: "Uganda",
        name_fr: "Ouganda",
        capital: "Kampala",
        capital_fr: "Kampala",
        currency: "UGX",
        currency_symbol: "USh",
        phone_code: "+256",
        flag_emoji: "🇺🇬",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 45741007,
        area_km2: 241038,
        languages: ["English", "Swahili"],
        coordinates: { lat: 1.3733, lng: 32.2903 },
        timezone: "Africa/Kampala",
        is_supported: true,
    },
    ZM: {
        country_code: "ZM",
        name: "Zambia",
        name_fr: "Zambie",
        capital: "Lusaka",
        capital_fr: "Lusaka",
        currency: "ZMW",
        currency_symbol: "ZK",
        phone_code: "+260",
        flag_emoji: "🇿🇲",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 18383955,
        area_km2: 752618,
        languages: ["English"],
        coordinates: { lat: -13.1339, lng: 27.8493 },
        timezone: "Africa/Lusaka",
        is_supported: true,
    },
    ZW: {
        country_code: "ZW",
        name: "Zimbabwe",
        name_fr: "Zimbabwe",
        capital: "Harare",
        capital_fr: "Harare",
        currency: "ZWL",
        currency_symbol: "$",
        phone_code: "+263",
        flag_emoji: "🇿🇼",
        region: "Africa",
        subregion: "Eastern Africa",
        population: 14862924,
        area_km2: 390757,
        languages: ["English", "Shona", "Ndebele"],
        coordinates: { lat: -19.0154, lng: 29.1549 },
        timezone: "Africa/Harare",
        is_supported: true,
    },
}

// Fonctions utilitaires pour les données des pays
export const getSupportedCountries = (): AfricanCountry[] => {
    return Object.values(AFRICA_COUNTRIES).filter(
        country => country.is_supported
    )
}

export const getCountryByCode = (code: string): AfricanCountry | undefined => {
    return AFRICA_COUNTRIES[code.toUpperCase()]
}

export const getCountriesByRegion = (region: string): AfricanCountry[] => {
    return Object.values(AFRICA_COUNTRIES).filter(country =>
        country.subregion.toLowerCase().includes(region.toLowerCase())
    )
}

export const getCountriesByLanguage = (language: string): AfricanCountry[] => {
    return Object.values(AFRICA_COUNTRIES).filter(country =>
        country.languages.some(lang =>
            lang.toLowerCase().includes(language.toLowerCase())
        )
    )
}

export const searchCountries = (query: string): AfricanCountry[] => {
    const searchTerm = query.toLowerCase()
    return Object.values(AFRICA_COUNTRIES).filter(
        country =>
            country.name.toLowerCase().includes(searchTerm) ||
            country.name_fr.toLowerCase().includes(searchTerm) ||
            country.capital.toLowerCase().includes(searchTerm) ||
            country.capital_fr.toLowerCase().includes(searchTerm)
    )
}

// Export par défaut
export default AFRICA_COUNTRIES
